/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cafe_POS;

import java.util.Calendar;
import java.util.GregorianCalendar;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Random;

/**
 *
 * @author kasgedeon
 */
public class Cafe_POS extends javax.swing.JFrame {
    
    double [] drink = new double[5];
    double [] cake = new double[6];
    double [] cost = new double[3];
    double [] total = new double[3];
    double [] i = new double[10];
    
    /**
     * Creates new form Cafe_POS
     */
    public Cafe_POS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        chLattle = new javax.swing.JCheckBox();
        chIcedLattle = new javax.swing.JCheckBox();
        chEspresso = new javax.swing.JCheckBox();
        chIcedCappuccino = new javax.swing.JCheckBox();
        chCappuccino = new javax.swing.JCheckBox();
        txtLattle = new javax.swing.JTextField();
        txtIcedLattle = new javax.swing.JTextField();
        txtEspresso = new javax.swing.JTextField();
        txtCappuccino = new javax.swing.JTextField();
        txtIcedCappuccino = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnReset = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnReceipt = new javax.swing.JButton();
        btnTotal = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtReceipt = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        subTotal = new javax.swing.JPanel();
        lblSubTotal = new javax.swing.JLabel();
        taxCost = new javax.swing.JPanel();
        lblTaxCost = new javax.swing.JLabel();
        totalCost = new javax.swing.JPanel();
        lblTotalCost = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        costOfDrinks = new javax.swing.JPanel();
        lblCostOfDrinks = new javax.swing.JLabel();
        costOfCakes = new javax.swing.JPanel();
        lblCostOfCakes = new javax.swing.JLabel();
        serviceCharge = new javax.swing.JPanel();
        lblServiceCharge = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        chCoffeeCake = new javax.swing.JCheckBox();
        chVanillaCake = new javax.swing.JCheckBox();
        chBananaCake = new javax.swing.JCheckBox();
        chRedVelvetCake = new javax.swing.JCheckBox();
        chBlackForestCake = new javax.swing.JCheckBox();
        txtCoffeeCake = new javax.swing.JTextField();
        txtVanillaCake = new javax.swing.JTextField();
        txtBananaCake = new javax.swing.JTextField();
        txtBlackForestCake = new javax.swing.JTextField();
        txtRedVelvetCake = new javax.swing.JTextField();
        chMangoCake = new javax.swing.JCheckBox();
        txtMangoCake = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 150));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        chLattle.setFont(new java.awt.Font("Century Gothic", 3, 12)); // NOI18N
        chLattle.setText("Lattle");
        chLattle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chLattleMouseClicked(evt);
            }
        });
        chLattle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chLattleActionPerformed(evt);
            }
        });

        chIcedLattle.setFont(new java.awt.Font("Century Gothic", 3, 12)); // NOI18N
        chIcedLattle.setText("Iced Lattle");
        chIcedLattle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chIcedLattleMouseClicked(evt);
            }
        });
        chIcedLattle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chIcedLattleActionPerformed(evt);
            }
        });

        chEspresso.setFont(new java.awt.Font("Century Gothic", 3, 12)); // NOI18N
        chEspresso.setText("Espresso");
        chEspresso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chEspressoMouseClicked(evt);
            }
        });

        chIcedCappuccino.setFont(new java.awt.Font("Century Gothic", 3, 12)); // NOI18N
        chIcedCappuccino.setText("Iced Cappuccino");
        chIcedCappuccino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chIcedCappuccinoMouseClicked(evt);
            }
        });

        chCappuccino.setFont(new java.awt.Font("Century Gothic", 3, 12)); // NOI18N
        chCappuccino.setText("Cappuccino");
        chCappuccino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chCappuccinoMouseClicked(evt);
            }
        });

        txtLattle.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        txtLattle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLattle.setText("0");

        txtIcedLattle.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        txtIcedLattle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIcedLattle.setText("0");

        txtEspresso.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        txtEspresso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEspresso.setText("0");

        txtCappuccino.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        txtCappuccino.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCappuccino.setText("0");

        txtIcedCappuccino.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        txtIcedCappuccino.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIcedCappuccino.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chLattle)
                    .addComponent(chIcedLattle)
                    .addComponent(chEspresso)
                    .addComponent(chCappuccino)
                    .addComponent(chIcedCappuccino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtCappuccino, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(txtEspresso, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIcedLattle, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIcedCappuccino)
                    .addComponent(txtLattle, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chLattle, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLattle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chIcedLattle, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIcedLattle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chEspresso, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEspresso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chCappuccino, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCappuccino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chIcedCappuccino, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIcedCappuccino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 250, 210));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 40)); // NOI18N
        jLabel1.setText("Au Beau Bar Café");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafe_POS/cafeBar.jpg"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Century Gothic", 2, 11)); // NOI18N
        jLabel9.setText("Chez Ged");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 291, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 870, 70));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        btnReset.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnReceipt.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnReceipt.setText("Receipt");
        btnReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReceiptActionPerformed(evt);
            }
        });

        btnTotal.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnTotal.setText("Total");
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReceipt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit)
                    .addComponent(btnReset)
                    .addComponent(btnReceipt)
                    .addComponent(btnTotal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, 320, 50));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        txtReceipt.setColumns(20);
        txtReceipt.setRows(5);
        jScrollPane1.setViewportView(txtReceipt);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, 320, 280));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, -1, -1));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setText("Sub Total");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setText("Tax");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setText("Total");

        subTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblSubTotal.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblSubTotal.setText("0.00");
        lblSubTotal.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout subTotalLayout = new javax.swing.GroupLayout(subTotal);
        subTotal.setLayout(subTotalLayout);
        subTotalLayout.setHorizontalGroup(
            subTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subTotalLayout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addComponent(lblSubTotal)
                .addContainerGap())
        );
        subTotalLayout.setVerticalGroup(
            subTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSubTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        taxCost.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTaxCost.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblTaxCost.setText("0.00");
        lblTaxCost.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout taxCostLayout = new javax.swing.GroupLayout(taxCost);
        taxCost.setLayout(taxCostLayout);
        taxCostLayout.setHorizontalGroup(
            taxCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, taxCostLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTaxCost)
                .addContainerGap())
        );
        taxCostLayout.setVerticalGroup(
            taxCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTaxCost, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        totalCost.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTotalCost.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblTotalCost.setText("0.00");
        lblTotalCost.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout totalCostLayout = new javax.swing.GroupLayout(totalCost);
        totalCost.setLayout(totalCostLayout);
        totalCostLayout.setHorizontalGroup(
            totalCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, totalCostLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTotalCost)
                .addContainerGap())
        );
        totalCostLayout.setVerticalGroup(
            totalCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTotalCost, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel2))
                .addGap(49, 49, 49)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(taxCost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalCost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(subTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(taxCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(totalCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 300, 120));

        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setText("Cost of Drinks");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setText("Cost of Cakes");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setText("Service Charge");

        costOfDrinks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblCostOfDrinks.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblCostOfDrinks.setText("0.00");
        lblCostOfDrinks.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout costOfDrinksLayout = new javax.swing.GroupLayout(costOfDrinks);
        costOfDrinks.setLayout(costOfDrinksLayout);
        costOfDrinksLayout.setHorizontalGroup(
            costOfDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, costOfDrinksLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(lblCostOfDrinks)
                .addContainerGap())
        );
        costOfDrinksLayout.setVerticalGroup(
            costOfDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCostOfDrinks, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        costOfCakes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblCostOfCakes.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblCostOfCakes.setText("0.00");
        lblCostOfCakes.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout costOfCakesLayout = new javax.swing.GroupLayout(costOfCakes);
        costOfCakes.setLayout(costOfCakesLayout);
        costOfCakesLayout.setHorizontalGroup(
            costOfCakesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, costOfCakesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCostOfCakes)
                .addContainerGap())
        );
        costOfCakesLayout.setVerticalGroup(
            costOfCakesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCostOfCakes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        serviceCharge.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblServiceCharge.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblServiceCharge.setText("0.00");
        lblServiceCharge.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout serviceChargeLayout = new javax.swing.GroupLayout(serviceCharge);
        serviceCharge.setLayout(serviceChargeLayout);
        serviceChargeLayout.setHorizontalGroup(
            serviceChargeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, serviceChargeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblServiceCharge)
                .addContainerGap())
        );
        serviceChargeLayout.setVerticalGroup(
            serviceChargeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblServiceCharge, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel7)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(costOfDrinks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(serviceCharge, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(costOfCakes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(costOfDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(costOfCakes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(serviceCharge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(16, 16, 16))
        );

        getContentPane().add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 230, 120));

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        chCoffeeCake.setFont(new java.awt.Font("Century Gothic", 3, 12)); // NOI18N
        chCoffeeCake.setText("Coffee Cake");
        chCoffeeCake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chCoffeeCakeMouseClicked(evt);
            }
        });

        chVanillaCake.setFont(new java.awt.Font("Century Gothic", 3, 12)); // NOI18N
        chVanillaCake.setText("Vanilla Cake");
        chVanillaCake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chVanillaCakeMouseClicked(evt);
            }
        });
        chVanillaCake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chVanillaCakeActionPerformed(evt);
            }
        });

        chBananaCake.setFont(new java.awt.Font("Century Gothic", 3, 12)); // NOI18N
        chBananaCake.setText("Banana Cake");
        chBananaCake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chBananaCakeMouseClicked(evt);
            }
        });

        chRedVelvetCake.setFont(new java.awt.Font("Century Gothic", 3, 12)); // NOI18N
        chRedVelvetCake.setText("Red Velvet Cake");
        chRedVelvetCake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chRedVelvetCakeMouseClicked(evt);
            }
        });

        chBlackForestCake.setFont(new java.awt.Font("Century Gothic", 3, 12)); // NOI18N
        chBlackForestCake.setText("Black Forest Cake");
        chBlackForestCake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chBlackForestCakeMouseClicked(evt);
            }
        });

        txtCoffeeCake.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        txtCoffeeCake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCoffeeCake.setText("0");

        txtVanillaCake.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        txtVanillaCake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtVanillaCake.setText("0");

        txtBananaCake.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        txtBananaCake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBananaCake.setText("0");

        txtBlackForestCake.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        txtBlackForestCake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBlackForestCake.setText("0");

        txtRedVelvetCake.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        txtRedVelvetCake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRedVelvetCake.setText("0");

        chMangoCake.setFont(new java.awt.Font("Century Gothic", 3, 12)); // NOI18N
        chMangoCake.setText("Mango Meringue Cake");
        chMangoCake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chMangoCakeMouseClicked(evt);
            }
        });

        txtMangoCake.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        txtMangoCake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMangoCake.setText("0");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chCoffeeCake)
                            .addComponent(chVanillaCake)
                            .addComponent(chBananaCake)
                            .addComponent(chBlackForestCake)
                            .addComponent(chRedVelvetCake))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBlackForestCake, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBananaCake, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVanillaCake, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCoffeeCake, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(txtRedVelvetCake))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(chMangoCake)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMangoCake)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chCoffeeCake)
                    .addComponent(txtCoffeeCake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chVanillaCake)
                    .addComponent(txtVanillaCake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chBananaCake)
                    .addComponent(txtBananaCake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chBlackForestCake)
                    .addComponent(txtBlackForestCake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chRedVelvetCake)
                    .addComponent(txtRedVelvetCake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chMangoCake)
                    .addComponent(txtMangoCake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 280, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chIcedLattleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chIcedLattleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chIcedLattleActionPerformed

    private void chVanillaCakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chVanillaCakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chVanillaCakeActionPerformed

    /**
     * reset forms button
    */
    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        lblCostOfDrinks.setText("0.00");
        lblCostOfCakes.setText("0.00");
        lblSubTotal.setText("0.00");
        lblTaxCost.setText("0.00");
        lblTotalCost.setText("0.00");
        txtCoffeeCake.setText("0");
        txtVanillaCake.setText("0");
        txtBananaCake.setText("0");
        txtBlackForestCake.setText("0");
        txtRedVelvetCake.setText("0");
        txtMangoCake.setText("0");
        txtLattle.setText("0");
        txtIcedLattle.setText("0");
        txtEspresso.setText("0");
        txtCappuccino.setText("0");
        txtIcedCappuccino.setText("0");
        chLattle.setSelected(false);
        chIcedLattle.setSelected(false);
        chEspresso.setSelected(false);
        chCappuccino.setSelected(false);
        chIcedCappuccino.setSelected(false);
        chCoffeeCake.setSelected(false);
        chVanillaCake.setSelected(false);
        chBananaCake.setSelected(false);
        chBlackForestCake.setSelected(false);
        chRedVelvetCake.setSelected(false);
        chMangoCake.setSelected(false);
        txtReceipt.setText(null);
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * generate receipt button
    */
    private void btnReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReceiptActionPerformed
        // TODO add your handling code here:
        drink[0] = Double.parseDouble(txtLattle.getText());
        drink[1] = Double.parseDouble(txtIcedLattle.getText());
        drink[2] = Double.parseDouble(txtEspresso.getText());
        drink[3] = Double.parseDouble(txtCappuccino.getText());
        drink[4] = Double.parseDouble(txtCappuccino.getText());
        
        cake[0] = Double.parseDouble(txtCoffeeCake.getText());
        cake[1] = Double.parseDouble(txtVanillaCake.getText());
        cake[2] = Double.parseDouble(txtBananaCake.getText());
        cake[3] = Double.parseDouble(txtBlackForestCake.getText());
        cake[4] = Double.parseDouble(txtRedVelvetCake.getText());
        cake[5] = Double.parseDouble(txtMangoCake.getText());
        
        cost[0] = Double.parseDouble(lblSubTotal.getText()); //Remove shs sign form string so that calculation may happen
        cost[1] = Double.parseDouble(lblTaxCost.getText());
        cost[2] = Double.parseDouble(lblTotalCost.getText());
        
        //===Reference number===
        int refs;
        refs = 1235 + (int) (Math.random()*4526);
        int ref = (refs);
        
        //===Transaction Time===
        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
        tTime.format(timer.getTime());
        SimpleDateFormat Tdate = new SimpleDateFormat("dd-MM-yyyy");
        Tdate.format(timer.getTime());
                
        
        txtReceipt.append("\n         "
                + "AU BEAU BAR CAFE\n" +
                "         ================\n\n" +
                "Reference:\t\t" + ref + "\n" +
                    "-------------------------"
                    + "---------------------------\n\n" +
                "Lattle:\t\t " + drink[0] + "\n" +
                "Iced Lattle:\t\t " + drink[1] + "\n" +
                "Espresso:\t\t " + drink[2] + "\n" +
                "Cappuccino:\t\t " + drink[3] + "\n" +
                "Iced Cappuccino:\t " + drink[4] + "\n" +            
                    "==============================\n" +             
                "Coffee Cake:\t\t " + cake[0] + "\n" +
                "Vanilla Cake:\t\t " + cake[1] + "\n" +
                "Banana  Cake:\t\t " + cake[2] + "\n" +
                "Black Forest Cake:\t " + cake[3] + "\n" +
                "Red Velvet Cake:\t " + cake[4] + "\n" +
                "Mango Meringue Cake:\t " + cake[5] + "\n" +
                    "==============================\n" +               
                "Sub Total:\t\t" + cost[0] + "\n" +
                "Tax:\t\t " + cost[1] + "\n" +
                "Total:\t\t" + cost[2] + "\n" +
                    "==============================\n" +
                "Date: " + Tdate.format(timer.getTime()) + "         " +
                " Time: " + tTime.format(timer.getTime()) +
                "\n\n\tThank You");
    }//GEN-LAST:event_btnReceiptActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void chLattleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chLattleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chLattleActionPerformed

    /**
     * prices of drinks
    */
    private void chCappuccinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chCappuccinoMouseClicked
        // TODO add your handling code here:
        double cCap = Double.parseDouble(lblCostOfDrinks.getText()); //actual total cost of drink
        double Cap = Double.parseDouble(txtCappuccino.getText()); //qty
        double iCap = 300; //cost of cappuccino
        
        if(chCappuccino.isSelected()){
            i[3] = (Cap * iCap) + cCap; // i -> Increment
            String pDrink = String.format("%.2f", i[3]); //new compiled cost of drinks
            lblCostOfDrinks.setText(pDrink);
            String cost = String.format("%.2f", (Cap * iCap)); //cost of cafe
            txtCappuccino.setText(cost);           
        }
    }//GEN-LAST:event_chCappuccinoMouseClicked

    private void chLattleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chLattleMouseClicked
        // TODO add your handling code here:
        double cLattle = Double.parseDouble(lblCostOfDrinks.getText());
        double Lattle = Double.parseDouble(txtLattle.getText()); //qty
        double iLattle = 199; //cost of lattle
        
        if(chLattle.isSelected()){
            i[0] = (Lattle * iLattle) + cLattle; // i -> Increment
            String pDrink = String.format("%.2f", i[0]); //compile cost of drinks
            lblCostOfDrinks.setText(pDrink);
            String cost = String.format("%.2f", (Lattle * iLattle)); //cost of cafe
            txtLattle.setText(cost);
        }
    }//GEN-LAST:event_chLattleMouseClicked

    private void chIcedLattleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chIcedLattleMouseClicked
        // TODO add your handling code here:
        double cIcedLattle = Double.parseDouble(lblCostOfDrinks.getText());
        double IcedLattle = Double.parseDouble(txtIcedLattle.getText()); //qty
        double iIcedLattle = 250; //cost of iced-lattle
        
        if(chIcedLattle.isSelected()){
            i[1] = (IcedLattle * iIcedLattle) + cIcedLattle; // i -> Increment
            String pDrink = String.format("%.2f", i[1]); //compile cost of drinks
            lblCostOfDrinks.setText(pDrink); //set new cost of drinks
            String cost = String.format("%.2f", (IcedLattle * iIcedLattle)); //cost of cafe
            txtIcedLattle.setText(cost);
        }
    }//GEN-LAST:event_chIcedLattleMouseClicked

    private void chEspressoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chEspressoMouseClicked
        // TODO add your handling code here:
        double cEspresso = Double.parseDouble(lblCostOfDrinks.getText());
        double Espresso = Double.parseDouble(txtEspresso.getText()); //qty
        double iEspresso = 250; //cost of espresso
        
        if(chEspresso.isSelected()){
            i[2] = (Espresso * iEspresso) + cEspresso; // i -> Increment
            String pDrink = String.format("%.2f", i[2]); //compile cost of drinks
            lblCostOfDrinks.setText(pDrink); //set new cost of drinks
            String cost = String.format("%.2f", (Espresso * iEspresso)); //cost of cafe
            txtEspresso.setText(cost);
        }
    }//GEN-LAST:event_chEspressoMouseClicked

    private void chIcedCappuccinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chIcedCappuccinoMouseClicked
        // TODO add your handling code here:
        double cIcedCap = Double.parseDouble(lblCostOfDrinks.getText());
        double IcedCap = Double.parseDouble(txtIcedCappuccino.getText()); //qty
        double iIcedCap = 350; //cost of espressp
        
        if(chIcedCappuccino.isSelected()){
            i[4] = (IcedCap * iIcedCap) + cIcedCap; // i -> Increment
            String pDrink = String.format("%.2f", i[4]); //compile cost of drinks
            lblCostOfDrinks.setText(pDrink); //set new cost of drinks
            String cost = String.format("%.2f", (IcedCap * iIcedCap)); //cost of cafe
            txtIcedCappuccino.setText(cost);
        }
    }//GEN-LAST:event_chIcedCappuccinoMouseClicked

    /**
     * prices of cakes
    */
    private void chCoffeeCakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chCoffeeCakeMouseClicked
        // TODO add your handling code here:
        double cCoffeeCake = Double.parseDouble(lblCostOfCakes.getText());
        double ICoffeeCake = Double.parseDouble(txtCoffeeCake.getText()); //qty
        double iCoffeeCake = 150; //cost of coffee-cake
        
        if(chCoffeeCake.isSelected()){
            i[5] = (ICoffeeCake * iCoffeeCake) + cCoffeeCake; // i -> Increment
            String pCake = String.format("%.2f", i[5]); //compile cost/price of cakes
            lblCostOfCakes.setText(pCake); //set new cost of cakes
            String cost = String.format("%.2f", (ICoffeeCake * iCoffeeCake)); //cost of cake
            txtCoffeeCake.setText(cost);
        }
    }//GEN-LAST:event_chCoffeeCakeMouseClicked

    private void chVanillaCakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chVanillaCakeMouseClicked
        // TODO add your handling code here:
        double cVanillaCake = Double.parseDouble(lblCostOfCakes.getText());
        double IVanillaCake = Double.parseDouble(txtVanillaCake.getText()); //qty
        double iVanillaCake = 250; //cost of vanilla-cake
        
        if(chVanillaCake.isSelected()){
            i[6] = (IVanillaCake * iVanillaCake) + cVanillaCake; // i -> Increment
            String pCake = String.format("%.2f", i[6]); //compile cost/price of cakes
            lblCostOfCakes.setText(pCake); //set new cost of cakes
            String cost = String.format("%.2f", (IVanillaCake * iVanillaCake)); //cost of cake
            txtVanillaCake.setText(cost);
        }
    }//GEN-LAST:event_chVanillaCakeMouseClicked

    private void chBananaCakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chBananaCakeMouseClicked
        // TODO add your handling code here:
        double cBananaCake = Double.parseDouble(lblCostOfCakes.getText());
        double BananaCake = Double.parseDouble(txtBananaCake.getText()); //qty
        double iBananaCake = 200; //cost of banana-cake
        
        if(chBananaCake.isSelected()){
            i[7] = (BananaCake * iBananaCake) + cBananaCake; // i -> Increment
            String pCake = String.format("%.2f", i[7]); //compile cost/price of cakes
            lblCostOfCakes.setText(pCake); //set new cost of cakes
            String cost = String.format("%.2f", (BananaCake * iBananaCake)); //cost of cake
            txtBananaCake.setText(cost);
        }
    }//GEN-LAST:event_chBananaCakeMouseClicked

    private void chBlackForestCakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chBlackForestCakeMouseClicked
        // TODO add your handling code here:
        double cBlackForestCake = Double.parseDouble(lblCostOfCakes.getText());
        double BlackForestCake = Double.parseDouble(txtBlackForestCake.getText()); //qty
        double iBlackForestCake = 300; //cost of black-forest cake
        
        if(chBlackForestCake.isSelected()){
            i[8] = (BlackForestCake * iBlackForestCake) + cBlackForestCake; // i -> Increment
            String pCake = String.format("%.2f", i[8]); //compile cost/price of cakes
            lblCostOfCakes.setText(pCake); //set new cost of cakes
            String cost = String.format("%.2f", (BlackForestCake * iBlackForestCake)); //cost of cake
            txtBlackForestCake.setText(cost);
        }
    }//GEN-LAST:event_chBlackForestCakeMouseClicked

    private void chRedVelvetCakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chRedVelvetCakeMouseClicked
        // TODO add your handling code here:
        double cRedVelvetCake = Double.parseDouble(lblCostOfCakes.getText());
        double RedVelvetCake = Double.parseDouble(txtRedVelvetCake.getText()); //qty
        double iRedVelvetCake = 250; //cost of red velvet cake
       
        if(chRedVelvetCake.isSelected()){
            i[9] = (RedVelvetCake * iRedVelvetCake) + cRedVelvetCake; // i -> Increment
            String pCake = String.format("%.2f", i[9]); //compile cost/price of cakes
            lblCostOfCakes.setText(pCake); //set new cost of cakes
            String cost = String.format("%.2f", (RedVelvetCake * iRedVelvetCake)); //cost of cake
            txtRedVelvetCake.setText(cost);
        }
    }//GEN-LAST:event_chRedVelvetCakeMouseClicked

    private void chMangoCakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chMangoCakeMouseClicked
        // TODO add your handling code here:
        double cMangoCake = Double.parseDouble(lblCostOfCakes.getText());
        double MangoCake = Double.parseDouble(txtMangoCake.getText()); //qty
        double iMangoCake = 150; //cost of mango cake
        
        if(chMangoCake.isSelected()){
            i[10] = (MangoCake * iMangoCake) + cMangoCake; // i -> Increment
            String pCake = String.format("%.2f", i[10]); //compile cost/price of cakes
            lblCostOfCakes.setText(pCake); //set new cost of cakes
            String cost = String.format("%.2f", (MangoCake * iMangoCake)); //cost of cake
            txtMangoCake.setText(cost);
        }
    }//GEN-LAST:event_chMangoCakeMouseClicked

    /**
     * compute total button
    */
    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        // TODO add your handling code here:
        total[0] = Double.parseDouble(lblCostOfDrinks.getText());
        total[1] = Double.parseDouble(lblCostOfCakes.getText());
        total[2] = Double.parseDouble(lblServiceCharge.getText());
        
        double cTotal = (total[0] + total[1] + total[2]); //total of all costs
        
        String iTaxTotal = String.format("%.2f", cTotal / 100); //tax calculation (1%)
        lblTaxCost.setText(iTaxTotal);
        
        double subTotal = (cTotal);
        String iSubTotal = String.format("%.2f", subTotal); //total before tax
        lblSubTotal.setText(iSubTotal);
        
        double allTotal = (subTotal + (cTotal/100));
        String iAllTotal = String.format("%.2f", allTotal); //total before tax
        lblTotalCost.setText(iAllTotal);
        
    }//GEN-LAST:event_btnTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cafe_POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cafe_POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cafe_POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cafe_POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cafe_POS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnReceipt;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTotal;
    private javax.swing.JCheckBox chBananaCake;
    private javax.swing.JCheckBox chBlackForestCake;
    private javax.swing.JCheckBox chCappuccino;
    private javax.swing.JCheckBox chCoffeeCake;
    private javax.swing.JCheckBox chEspresso;
    private javax.swing.JCheckBox chIcedCappuccino;
    private javax.swing.JCheckBox chIcedLattle;
    private javax.swing.JCheckBox chLattle;
    private javax.swing.JCheckBox chMangoCake;
    private javax.swing.JCheckBox chRedVelvetCake;
    private javax.swing.JCheckBox chVanillaCake;
    private javax.swing.JPanel costOfCakes;
    private javax.swing.JPanel costOfDrinks;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCostOfCakes;
    private javax.swing.JLabel lblCostOfDrinks;
    private javax.swing.JLabel lblServiceCharge;
    private javax.swing.JLabel lblSubTotal;
    private javax.swing.JLabel lblTaxCost;
    private javax.swing.JLabel lblTotalCost;
    private javax.swing.JPanel serviceCharge;
    private javax.swing.JPanel subTotal;
    private javax.swing.JPanel taxCost;
    private javax.swing.JPanel totalCost;
    private javax.swing.JTextField txtBananaCake;
    private javax.swing.JTextField txtBlackForestCake;
    private javax.swing.JTextField txtCappuccino;
    private javax.swing.JTextField txtCoffeeCake;
    private javax.swing.JTextField txtEspresso;
    private javax.swing.JTextField txtIcedCappuccino;
    private javax.swing.JTextField txtIcedLattle;
    private javax.swing.JTextField txtLattle;
    private javax.swing.JTextField txtMangoCake;
    private javax.swing.JTextArea txtReceipt;
    private javax.swing.JTextField txtRedVelvetCake;
    private javax.swing.JTextField txtVanillaCake;
    // End of variables declaration//GEN-END:variables
}
